### ISSUE TITLE
Plan for 2.0.0-M10

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#1370]
A 2.0.0-M10 released was proposed at https://github.com/eclipse/leshan/issues/1222#issuecomment-1327715281

Mid-December was proposed at : https://github.com/eclipse/leshan/pull/1326#issuecomment-1342498697
That's sounds a bit short but we can try.
If we see there is no time enough, I strongly encourage to delay instead of releasing in a rush. 

Current modification are :
```
3a9d48cf8: GH-1359: Add Application Data support to Bootstrap Server Authorizer
05dbddb80: GH-1359: Create Authorizer for Bootstrap server
7547de54e: GH-1293: Enhance ApplicationData support (new Authorizer API)
008cdb830: Delete old Github Workflow on the 1st day of the month.
e644ae3e4: "Comment PR" workflow should not be run if "Check PR" is skipped
3afc6382f: Add github issue template.
116633aa2: Add github pull request template.
07d867c3b: Update some demo front end dependency (dependatbot security issue)
1a2025f3a: Add Social Preview for Leshan
5877f57d8: GH-1352: Fix invalid default value of resources 120, 1120 of 3442 object
0aae0536b: GH-1350: Update Identity key in Redis when client IP address has changed
c13c5043c: Rename EPL license to make github detect it.
fdef2201e: GH-1314: Fix Github action issue about adding comment on PR.
07b747390: Add a new Write Integration tests.
76dc37004: Fix regression in toString() of LWM2M Value introduced in GH_1321
3bb6ac40a: Activate can_write_multi_instance_objlnk_resource test for all format.
fbdaa96a9: Upgrade to jetty 9.4.49.v20220914
403ef5b5d: GH-1339: Upgrade to slf4j 2.x
90eb405c2: Update LICENSE files.
746c43b68: Update SECURITY.md to add CVE-2022-39368
f27b49ddf: Update Web Demo dependencies
7b0efd399: Update Jackson to 2.14.0.
c8c661fe3: Add minimal Java version to README.md
a314ff2fc: GH-1333: Prevent NPE in RedisStore Registration Cleaner
122a1a855: Typo: boostrap/bootstap => bootstrap
2cafa2c32: GH-1320: Improve toString for core link resources
45cbe1b7c: GH-1322: Add Checkstyle rule to ensure Java files get right header
8cf38b301: Fix Java File Header
```

~Missing tasks :~
- [x] integrate  #1326 to fix #1325  (Done)
- [x] #678 ~(I'm working on it~  Done  based on :point_up: ), see #1371 
- [x] #1348 (~I plan to do it just after~ Done) see #1372

@Warmek, @JaroslawLegierski please do not hesitate to share if I missed something ?

@JaroslawLegierski you also said  (https://github.com/eclipse/leshan/issues/1222#issuecomment-1329456497) : 
> Today we also identified one problem with Californium congestion control but I haven't analyzed this problem yet and I don't know if it concerns Leshan or Cf ? (I will test it tomorrow or the day after tomorrow)

I don't think "having a fix for this + a release of californium + integration in leshan"  is compatible with Mid-December  ?
(maybe @boaks can confirm)

**Comment by boaks** [comment]
I don't plan a Californium release next week. 
Maybe end of the year.

**Comment by sbernard31** [comment]
#1371  ready for review. (aims to implement #678)

#1372 ready for review. (aims to implements #1348)

**Comment by sbernard31** [comment]
AFAIK, all tasks for **2.0.0-M10** are done.

> Yes our colleagues are ready to test all new features - as soon as they are available in the master branch.

Except if I missed something I think `master` is ready for tests.

**Comment by sbernard31** [comment]
@JaroslawLegierski, @Warmek , let me know when I have green light to launch **2.0.0-M10** 
(on my side there is no urgency)

**Comment by sbernard31** [comment]
@JaroslawLegierski, @Warmek just to let you know that I will be unavailable from 23th December (22th is my last day for 2022).
I'm back the 4th January. So I will not be able to release during this period.

**Comment by JaroslawLegierski** [comment]
We just have received information that the 2.0.0-M10 release has been successfully tested
We have only one small remark - there are 2  missing descriptions:
GH-678: Enhance Base64 support
GH-1325: Fix Base64 from SenML-JSON 
Both fixes are in the M10 (master) but they are missed in the 2.0.0-M10 description (list above).

**Comment by sbernard31** [comment]
Yes it is the changes logs at moment I created the issue.
The 2.0.0-M10 will contain everything which is in `master` now : 
```
924da186f: GH-1348: Add new constructor to SenMLJsonJacksonEncoderDecoder
ce9892402: GH-678: Enhance Base64 support & GH-1325: Fix Base64 from SenML-JSON.
e7f1ac415: Enhance SenMLTestUtil to display byte[] value in Hexa.
3a9d48cf8: GH-1359: Add Application Data support to Bootstrap Server Authorizer
05dbddb80: GH-1359: Create Authorizer for Bootstrap server
7547de54e: GH-1293: Enhance ApplicationData support (new Authorizer API)
008cdb830: Delete old Github Workflow on the 1st day of the month.
e644ae3e4: "Comment PR" workflow should not be run if "Check PR" is skipped
3afc6382f: Add github issue template.
116633aa2: Add github pull request template.
07d867c3b: Update some demo front end dependency (dependatbot security issue)
1a2025f3a: Add Social Preview for Leshan
5877f57d8: GH-1352: Fix invalid default value of resources 120, 1120 of 3442 object
0aae0536b: GH-1350: Update Identity key in Redis when client IP address has changed
c13c5043c: Rename EPL license to make github detect it.
fdef2201e: GH-1314: Fix Github action issue about adding comment on PR.
07b747390: Add a new Write Integration tests.
76dc37004: Fix regression in toString() of LWM2M Value introduced in GH_1321
3bb6ac40a: Activate can_write_multi_instance_objlnk_resource test for all format.
fbdaa96a9: Upgrade to jetty 9.4.49.v20220914
403ef5b5d: GH-1339: Upgrade to slf4j 2.x
90eb405c2: Update LICENSE files.
746c43b68: Update SECURITY.md to add CVE-2022-39368
f27b49ddf: Update Web Demo dependencies
7b0efd399: Update Jackson to 2.14.0.
c8c661fe3: Add minimal Java version to README.md
a314ff2fc: GH-1333: Prevent NPE in RedisStore Registration Cleaner
122a1a855: Typo: boostrap/bootstap => bootstrap
2cafa2c32: GH-1320: Improve toString for core link resources
45cbe1b7c: GH-1322: Add Checkstyle rule to ensure Java files get right header
8cf38b301: Fix Java File Header
```

Just to be sure does it means I can start release process for 2.0.0-M10 ?

**Comment by JaroslawLegierski** [comment]
> Just to be sure does it mean I can start release process for 2.0.0-M10 ?

Yes of course - you can start new release 2.0.0-M10

**Comment by sbernard31** [comment]
:warning: I face a little issue with 2.0.0-M10 release process : https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2427

**Comment by JaroslawLegierski** [comment]
Maybe this problem is network related? Are you using a proxy server?

**Comment by sbernard31** [comment]
All of this is executed by **jenkins** instance hosted by eclipse, so I don't know if there is proxy involved somewhere. 
That was working before. For now my bet this is rather a right access issue with **eclipse-leshan-bot**.

**Comment by sbernard31** [comment]
- :heavy_check_mark:  The issue was fixed by eclipse IT team.
 - :heavy_check_mark:  The release process succeed at jenkins level.
 - :construction:  The release process is ongoing at sonatype level.
 
So the release should be available on maven central tomorrow morning. (even If I haven't communicate on it)

**Comment by sbernard31** [comment]
The [2.0.0-M10 artifacts](https://search.maven.org/search?q=g:org.eclipse.leshan%20AND%20v:2.0.0-M10%20AND%20!a:leshan) are available on maven central.

**Comment by sbernard31** [comment]
I added the release information : https://github.com/eclipse/leshan/releases/tag/leshan-2.0.0-M10

But I wait for https://github.com/eclipse/leshan/issues/1222#issuecomment-1357861361 answer before to communicate on it. 
(as I would like to talk about this with the release announce)

**Comment by jvermillard** [comment]
late to the party, but I rebased my "obj25" branch on master, fixed conflict :sweat_smile: , bumped my product to use it, ran my integration test suite, looks all green to me :+1:

**Comment by sbernard31** [comment]
Ok so now first version of transport layer abstraction is in `master` and I was able to communicate about **2.0.0-M10**.

I think we can close this.

Thx guys for your help :pray:
